events {}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;

        # Frontend estático (React build)
        location / {
            root   /usr/share/nginx/html;
            try_files $uri /index.html;
        }

        # Microservicios (enrutamiento por path)
        location /api/create/   { proxy_pass http://create-person:8000/; }
        location /api/update/   { proxy_pass http://update-person:8000/; }
        location /api/query/    { proxy_pass http://query-person:8000/;  }
        location /api/delete/   { proxy_pass http://delete-person:8000/; }
        location /api/log/      { proxy_pass http://log-service:8000/;   }
    }
}
